name: Setup WSL
description: Setup WSL2 environment with Docker support

runs:
  using: composite
  steps:
    - name: configure WSL
      shell: pwsh
      run: |
        $config = @"
        [wsl2]
        memory=4GB
        swap=0
        networkingMode=mirrored
        "@
        $config | Out-File -Append -FilePath "$env:USERPROFILE\.wslconfig" -Encoding ASCII
        cat "$env:USERPROFILE\.wslconfig"

    - uses: vampire/setup-wsl@6a8db447be7ed35f2f499c02c6e60ff77ef11278 # v6.0.0
      with:
        distribution: Ubuntu-24.04
        use-cache: true
        set-as-default: true

    - name: setup docker CE
      shell: wsl-bash {0}
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl jq
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc

        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

        # 1. Configure daemon.json for nftables backend and IP forwarding
        # Note: nftables backend does not enable ip-forward by default, so we force it.
        echo '{ "firewall-backend": "nftables", "ip-forward": true }' | sudo tee /etc/docker/daemon.json

        # 2. Modify Systemd Service to listen on TCP 2375
        # This exposes the daemon so Windows can talk to it.
        sudo sed -i 's|-H fd://|-H fd:// -H tcp://0.0.0.0:2375|' /lib/systemd/system/docker.service

        # 3. Reload and Restart
        sudo systemctl daemon-reload
        sudo systemctl enable docker.service
        sudo systemctl start docker.service

        sudo ip addr

        export DOCKER_HOST=tcp://127.0.0.1:2375
        docker context ls
        # 4. Health Check Loop
        echo "Waiting for Docker Daemon..."
        for i in {1..30}; do
          if sudo docker info > /dev/null 2>&1; then
            echo "Docker Daemon is ACTIVE."
            exit 0
          fi
          echo "Waiting... ($i/30)"
          sleep 1
        done
        echo "Docker Daemon failed to start."
        exit 1

    - name: allow docker access from Windows
      shell: pwsh
      run: |
        echo "DOCKER_HOST=tcp://127.0.0.1:2375" >> $env:GITHUB_ENV

    - name: Verify Docker Bridge from Windows
      shell: pwsh
      run: |
        # Keep wsl alive for the step
        Start-Job -ScriptBlock { wsl sleep infinity } | Out-Null
        wsl --list --verbose
        docker context ls
        docker version
        docker pull envoyproxy/envoy:linux-amd64
        wsl --list --verbose
        docker inspect envoyproxy/envoy:linux-amd64 | Select-String "Architecture"
