name: Build Windows Envoy
description: Build Envoy for Windows using Bazel

inputs:
  version:
    description: "Envoy version to build"
    required: true
  repository:
    description: "GitHub repository to clone Envoy from"
    required: false
    default: "envoyproxy/envoy"
  patch:
    description: "Whether to apply patches"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.version }}
        path: out/envoy-build

    #- uses: bazel-contrib/setup-bazel@4fd964a13a440a8aeb0be47350db2fc640f19ca8 # 0.15.0
    #  with:
    #    disk-cache: ${{ inputs.version }}
    #    repository-cache: true

    - name: Apply patches
      shell: bash
      if: ${{ inputs.patch == 'true' }}
      run: |
        cp envoy_windows_fixes.patch out/envoy-build/
        cd out/envoy-build
        git apply envoy_windows_fixes.patch

    - name: build envoy
      working-directory: out/envoy-build
      shell: pwsh
      run: |
        # Bazel runs many commands in bash, which prepends the unix tools to the beginning of the path.
        # This includes a `link.exe` that is gnu, not the MSVC or LLVM one we need. We replace it with
        # a symlink to the correct one.
        Remove-Item "C:\msys64\usr\bin\link.exe" -ErrorAction Ignore
        New-Item -Path "C:\msys64\usr\bin\link.exe" -ItemType SymbolicLink -Value "C:\Program Files\LLVM\bin\lld-link.exe"

        $env:Path="C:\msys64\usr\bin;$env:Path"
        $env:BAZEL_SH="C:\msys64\usr\bin\bash.exe"
        $env:BAZEL_LLVM="C:\Program Files\LLVM"

        bash.exe -c "which xargs"

        # Run the build
        bazel build -c opt --sandbox_debug `
          --extra_toolchains=@local_config_cc//:cc-toolchain-x64_windows-clang-cl `
          --extra_execution_platforms=//bazel/platforms:x64_windows-clang-cl `
          --action_env=PATH `
          --noincompatible_strict_action_env `
          --action_env=TMPDIR `
          --enable_runfiles=yes `
          --features=compiler_param_file `
          --features=fully_static_link `
          --features=static_link_msvcrt `
          --dynamic_mode=off `
          --define signal_trace=disabled `
          --define hot_restart=disabled `
          --define tcmalloc=disabled `
          --define wasm=disabled `
          --define manual_stamp=manual_stamp `
          --cxxopt=/std:c++20 `
          --host_cxxopt=/std:c++20 `
          --copt=-Wno-error=implicit-function-declaration `
          --copt=-Wno-unknown-argument `
          --copt=-Wno-nullability-completeness `
          --copt=-Wno-unused-command-line-argument `
          --copt=-Wno-macro-redefined `
          --copt=-Wno-builtin-macro-redefined `
          --cxxopt=/FIstring `
          --per_file_copt=source/extensions/http/ext_proc/.*@-Wno-nontrivial-memcall `
          --per_file_copt=source/extensions/filters/common/expr/.*@-Wno-nontrivial-memcall `
          --per_file_copt=source/extensions/filters/http/ext_proc/.*@-Wno-nontrivial-memcall `
          --per_file_copt=source/extensions/tracers/opentelemetry/samplers/cel/.*@-Wno-nontrivial-memcall `
          --per_file_copt=external/com_google_cel_cpp/.*@/DWIN32_LEAN_AND_MEAN `
          --per_file_copt=external/com_google_cel_cpp/.*@/DNOUSER `
          --per_file_copt=external/com_google_cel_cpp/.*@/DNOGDI `
          --verbose_failures `
          --curses=no `
          envoy

    - if: always()
      shell: pwsh
      working-directory: out/envoy-build
      run: |
        ls bazel-out/x64_windows-opt-exec-ST-a4acdbd19b2a/bin/external/rules_foreign_cc/toolchains/private/pkgconfig.build_tmpdir
        cat bazel-out/x64_windows-opt-exec-ST-a4acdbd19b2a/bin/external/rules_foreign_cc/toolchains/private/pkgconfig.build_tmpdir/configure

    # When linking a dynamic module, it will import envoy.dll. The easiest way to deal
    # with this is name the actual executable envoy.dll - Windows will run it as a binary
    # just fine.
    - run: cp out/envoy-build/bazel-bin/source/exe/envoy-static.exe envoy/_bin/envoy.dll
      shell: pwsh
