name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write

jobs:
  build-unix:
    runs-on: ubuntu-24.04
    environment: ${{ github.event_name == 'push' && 'prod' || 'dev' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

      - name: Build wheels
        run: uv run poe unix-wheels

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: unix-wheels
          path: dist/

  build-windows:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

      - id: envoy-version
        shell: bash
        run: echo "version=$(uv run poe print-envoy-version)" >> $GITHUB_OUTPUT

      - uses: ./.github/actions/build-windows
        with:
          version: ${{ steps.envoy-version.outputs.version }}
          patch: .github/actions/build-windows/v1.37.patch

      - name: Build wheel
        run: uv run poe build

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: windows-wheels
          path: dist/

  publish:
    needs:
      - build-unix
      - build-windows
    runs-on: ubuntu-24.04
    environment: ${{ github.event_name == 'push' && 'prod' || 'dev' }}
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist/
          merge-multiple: true

      # Only supports unix runner
      - uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          repository-url: ${{ github.event_name != 'push' && 'https://test.pypi.org/legacy/' || null }}
          skip-existing: ${{ github.event_name != 'push' }}
